### ISSUE TITLE
How soon is the code release?

### ISSUE THREAD

**Issue by detectRecog** [PRIS-CV/AFGR#1]
Hello, I've been following you for a long time. How soon is the code release?

**Comment by RuoyiDu** [comment]
Not very soon... The paper is going to be submitted to the journal. And the code will be released once we submit it.

**Comment by RuoyiDu** [comment]
> Hello, I've been following you for a long time. How soon is the code release?

Not very soon... The paper is going to be submitted to the journal. And the code will be released once we submit it.
